interface AppConfig {
  MAX_LOGIN_ATTEMPTS: number;
  NEW_NOTIFICATION_THRESHOLD_IN_HOURS: number;
  MIN_DISCOUNT_PERCENTAGE_FOR_ANALYTICS: number;
}

export const config: AppConfig = {
  MAX_LOGIN_ATTEMPTS: 5,
  NEW_NOTIFICATION_THRESHOLD_IN_HOURS: 24,
  MIN_DISCOUNT_PERCENTAGE_FOR_ANALYTICS: 10,
};
